version: "3.7"
services:
  nest-server:
    build: .
    tty: true
    ports:
      - 3222:3000
      - 5555:5555
    volumes:
      - ./server:/server
      # nest-serverサービスが、dbサービスの起動後に起動するように設定
    depends_on:
      - db
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    # コンテナが停止しても自動で再起動するように設定
    restart: always
    ports:
      - 5777:5432
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - ./db/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env.exapmle
    # PostgreSQLの環境変数を設定
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
