version: "3.7"
services:
  nest-server:
    build: .
    tty: true
    ports:
      - 3222:3000
      - 5555:5555
    volumes:
      - ./server:/server
      # nest-serverサービスが、dbサービスの起動後に起動するように設定
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
    networks:
      - app-network
    depends_on:
      - db
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    # コンテナが停止しても自動で再起動するように設定
    restart: always
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./db/postgres/init.d:/docker-entrypoint-initdb.d
      - ./db/postgres/data:/var/lib/postgresql/data
    # PostgreSQLの環境変数を設定
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

networks:
  app-network:
    driver: bridge
